# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinycontent', '0003_update_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tinycontent',
            options={'permissions': (('can_change_title', 'Can change Title'),), 'verbose_name': 'Content block'},
        ),
    ]
